#!/usr/bin/env python3

from tempfile import mktemp
from json import dump
from sys import argv, stdin, stdout, stderr
from subprocess import run

fname = mktemp()
print(fname)
with open(fname, 'w') as f:
    dump(argv[1:], f)

run(['su', '-', 'lucasew', '-c', f"deroot_out {fname}"], stdin = stdin, stdout = stdout, stderr = stderr)

