#!/usr/bin/env python3

"""
Wrapper script (root to non-root). Dumps the root user's execution environment into a temporary JSON file and transitions execution context to `colab` user via `su`.
This is necessary because Google Colab runs as root, which can cause issues with Nix.
"""

from tempfile import mktemp
from json import dump
from sys import argv, stdin, stdout, stderr
from subprocess import Popen
from os import environ

fname = mktemp()
state = dict(env={}, argv=argv[1:])
for (k, v) in environ.items():
    state['env'][k] = v

with open(fname, 'w') as f:
    dump(state, f)

p = Popen(['su', '-', 'colab', '-c', f"deroot_out {fname}"], stdin = stdin, stdout = stdout, stderr = stderr)
p.wait()

